In [6]:
import pandas as pd

In [9]:
df = pd.read_json('weather-station-test.json', lines=True)

In [11]:
df.describe()

,humidity,pressure,rainfall,temperature,wind_direction_avg,wind_speed_avg,wind_speed_last,wind_speed_max
count,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000
mean,56.417129,1006.479612,0.006334,17.557544,51.532738,0.000460,0.000746,0.001865
std,1.860980,5.235056,0.262592,0.305214,36.369457,0.015945,0.042333,0.062342
min,52.296395,994.743228,0.000000,16.972688,42.199138,0.000000,0.000000,0.000000
25%,54.892568,1003.684983,0.000000,17.308963,45.000000,0.000000,0.000000,0.000000
50%,56.895387,1008.277129,0.000000,17.675354,45.000000,0.000000,0.000000,0.000000
75%,58.065034,1010.887450,0.000000,17.795812,45.000000,0.000000,0.000000,0.000000
max,60.088212,1012.260571,12.852400,18.081900,309.563168,0.760693,2.402187,2.402187